environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
